remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Nikhil Yadav]
description: [Building innovative solutions with Flutter, AI, and creative design. Passionate about data science and user experience.]
